blank_issues_enabled: false
contact_links:
  - name: Contributing Guidelines
    url: https://github.com/kaic/win-post-install/blob/main/CONTRIBUTING.md
    about: Please read our contributing guidelines before opening an issue.
